### ISSUE TITLE
How to use ESP 32 and Arduino UNO ?

### ISSUE THREAD

**Issue by matthew1205** [ubidots/ubidots-arduino-ethernet#7]
Hi

Thanks to Arduino UNO and Ethernet shield 1 for providing a library that makes it easy to use Ubidots.
I would like to use this library in ESP32 or Arduino M0.
Can you update the library for use with ESP32 or Arduino M0?
Or can you tell me how to use it in ESP32 or Arduino M0?

Thank you.

Best Regards
Matthew

**Comment by jotathebest** [comment]
This library is for the Ethernet shield, it makes no sense to put an issue related with ESP32.

Closing
